### ISSUE TITLE
resource/aws_msk_cluster: Add storage_mode argument

### ISSUE THREAD

**Issue by posquit0** [tedilabs/terraform-aws-misc#28]
- https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.40.0
- https://github.com/hashicorp/terraform-provider-aws/issues/27546

**Comment by cbrim-12** [comment]
Still open?

**Comment by posquit0** [comment]
@cbrim-12 This module was migrated to `tedilabs/terraform-aws-messaging` repository.

You can check the following URL:
https://github.com/tedilabs/terraform-aws-messaging/blob/main/modules/msk-cluster/variables.tf#L97
